version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-django_app_dev}
      POSTGRES_USER: ${POSTGRES_USER:-dev_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
    restart: unless-stopped

  web:
    image: ${ECR_REGISTRY:-123456789012.dkr.ecr.eu-west-1.amazonaws.com}/django-rest-app-web:latest
    command: ./entrypoint.sh gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - static_volume_dev:/app/staticfiles
    environment:
      - DEBUG=${DEBUG:-True}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-dev-secret-key}
      - POSTGRES_DB=${POSTGRES_DB:-django_app_dev}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: ${ECR_REGISTRY:-123456789012.dkr.ecr.eu-west-1.amazonaws.com}/django-rest-app-nginx:latest
    volumes:
      - static_volume_dev:/app/staticfiles
    depends_on:
      - web
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data_dev:
  static_volume_dev: