name: "Setup Python"

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.11'
  cache-dependency-path:
    description: 'Cache dependency path'  
    required: false
    default: '**/requirements.txt'

runs:
  using: "composite"
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install dependencies
      shell: bash
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django pytest-cov black flake8 mypy